name: gourmet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  envied: ^0.5.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  http: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  xml: ^6.5.0
  xml2json: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true
